version: "3.1"

services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./code:/code

        # Change site.conf to the site you are trying to get up running(also matching the file site.conf in the root directory)
      - ./site.conf:/etc/nginx/conf.d/site.conf

  php:
    build: "./docker/php"
    volumes:
      - ./code:/code
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      # Change to whathever your need is:
      MYSQL_ROOT_PASSWORD: SuperSecure
      MYSQL_DATABASE: craft
      MYSQL_USER: craftuser
      MYSQL_PASSWORD: craft

      # Uncomment to enable a web-based database manager
  #adminer:
  #image: adminer
  #restart: always
  #ports:
  #- 8080:8080
